➡️ 深度学习数据处理📊

生成张量

In [196]:
import torch
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [197]:
x = torch.arange(24).reshape(2, 3, 4) #构建多轴矩阵
x

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

显示数据格式

In [198]:
x = torch.arange(12)
x.shape # x = x.size()也可以显示张量的形状
# 形状是一个元组

torch.Size([12])

In [ ]:
x.numel() # 计算元素个数

12

更改数据格式

In [200]:
X= x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [249]:
X.T # 转置

tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])

张量赋值和常用计算方法

In [201]:
x = torch.zeros((2,3,4))
x

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [202]:
x = torch.ones((2,4,5))
x

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [ ]:
x = torch.tensor([1.0,2,3,4])
y = torch.tensor([3,5,6,7])
x+y, x-y, x*y, x/y, x**y #四则运算和幂运算

(tensor([ 4.,  7.,  9., 11.]),
 tensor([-2., -3., -3., -3.]),
 tensor([ 3., 10., 18., 28.]),
 tensor([0.3333, 0.4000, 0.5000, 0.5714]),
 tensor([1.0000e+00, 3.2000e+01, 7.2900e+02, 1.6384e+04]))

In [204]:
torch.exp(x) #指数计算

tensor([ 2.7183,  7.3891, 20.0855, 54.5982])

In [205]:
len(x) # length of x

4

In [206]:
x.sum() # 对x求和，不论x的形状如何，x.sum()都返回一个标量

tensor(10.)

=======================================================================================================================================

对特定轴进行求和

In [207]:
x = torch.arange(24, dtype=torch.float32).reshape(2,3,4)
x_sum_axis0 = x.sum(axis=0) # 对x的第0轴求和(以第0轴的向量整体求和)
x_sum_axis1 = x.sum(axis=1) # 对x的第1轴求和
x_sum_axis01 = x.sum(axis=(0,1)) # 对第0轴和第1轴求和, 先对第0轴求和，再对第1轴求和
x, x_sum_axis0, x_sum_axis1, x_sum_axis01

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.]],
 
         [[12., 13., 14., 15.],
          [16., 17., 18., 19.],
          [20., 21., 22., 23.]]]),
 tensor([[12., 14., 16., 18.],
         [20., 22., 24., 26.],
         [28., 30., 32., 34.]]),
 tensor([[12., 15., 18., 21.],
         [48., 51., 54., 57.]]),
 tensor([60., 66., 72., 78.]))

In [208]:
x.cumsum(axis=0) # 对x的第0轴求和(以第0轴的向量整体求和，[0，x, x]不变，[1，x, x]累加)

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 14., 16., 18.],
         [20., 22., 24., 26.],
         [28., 30., 32., 34.]]])

对特定轴/维度求均值

In [209]:
x_mean = x.mean() # 对x求均值
x_mean_axis0 = x.mean(axis=0) # 对x的第0轴求均值,x.mean(axis=0)=x.sum(axis=0)/x.shape[0]
x, x_mean_axis0


(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.]],
 
         [[12., 13., 14., 15.],
          [16., 17., 18., 19.],
          [20., 21., 22., 23.]]]),
 tensor([[ 6.,  7.,  8.,  9.],
         [10., 11., 12., 13.],
         [14., 15., 16., 17.]]))

计算总值和均值维度不变

In [210]:
x_sum_axis1 = x.sum(axis=1, keepdim=True) # 对x的第1轴求和, keepdim=True表示保持原有的维度
x_sum_axis1.shape, x_sum_axis1 # x_sum_axis1的形状是(2,1,4), x的形状是(2,3,4), 使可以继续进行广播

(torch.Size([2, 1, 4]),
 tensor([[[12., 15., 18., 21.]],
 
         [[48., 51., 54., 57.]]]))

点积是🌟向量🌟按元素相乘的和, 此时x为向量

In [247]:
x = torch.arange(12, dtype=torch.float32)
y = torch.ones(12, dtype=torch.float32)
x, y, torch.dot(x, y) # torch.dot(x, y)表示对x和y进行点积运算,x, y都是向量

(tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]),
 tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 tensor(66.))

In [250]:
torch.sum(x*y) # x和y都是向量, torch.sum(x*y)表示对x和y进行逐元素相乘后求和

tensor(66.)

矩阵向量积Ax是一个长度为m的列向量，A为m*n

In [258]:
A = torch.arange(20, dtype=torch.float32).reshape(5,4)
x = torch.arange(4, dtype=torch.float32)
A.shape, x.shape, torch.mv(A,x) # A是一个5*4的矩阵，x是一个4维的向量, mv表示矩阵和向量的乘法(matrix-vector multiplication)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

矩阵-矩阵乘法AB

In [260]:
B = torch.arange(24, dtype=torch.float32).reshape(4,6)
torch.mm(A, B) # A是一个5*4的矩阵，B是一个4*6的矩阵, mm表示矩阵和矩阵的乘法(matrix-matrix multiplication)

tensor([[  84.,   90.,   96.,  102.,  108.,  114.],
        [ 228.,  250.,  272.,  294.,  316.,  338.],
        [ 372.,  410.,  448.,  486.,  524.,  562.],
        [ 516.,  570.,  624.,  678.,  732.,  786.],
        [ 660.,  730.,  800.,  870.,  940., 1010.]])

L2范数是向量元素平方和的平方根

In [261]:
u = torch.tensor([3.0, -4.0])
norm_L2 = torch.norm(u) # 计算u的范数, torch.norm(u)表示对u进行范数计算
norm_Frobenius = torch.norm(A) # 计算A的Frobenius范数, torch.norm(A)表示对A进行Frobenius范数计算
norm_L2, norm_Frobenius

(tensor(5.), tensor(49.6991))

L1范数是元素绝对值的和

In [255]:
torch.abs(u).sum() # 计算u的绝对值之和

tensor(7.)

=======================================================================================================================================

处理张量

In [213]:
X = torch.arange(12,dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0,3,4,7],[3,4,5,6],[1,7,3,2]])
torch.cat((X, Y), dim=0),torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  3.,  4.,  7.],
         [ 3.,  4.,  5.,  6.],
         [ 1.,  7.,  3.,  2.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  3.,  4.,  7.],
         [ 4.,  5.,  6.,  7.,  3.,  4.,  5.,  6.],
         [ 8.,  9., 10., 11.,  1.,  7.,  3.,  2.]]))

In [214]:
X == Y # 布尔值运算

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

元素索引和矩阵特定赋值

In [215]:
X[0:3],X[-1] # -1可以用来访问张量最后一行，0:3访问前三行

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([ 8.,  9., 10., 11.]))

In [216]:
X[2,3] = 9 # 用来对第三行，第四列的数字进行重写
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10.,  9.]])

In [217]:
X[:2, :] = 12 #用来对多个元素赋值相同值
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10.,  9.]])

两个张量形状不同，仍然可以使用广播机制

In [218]:
a = torch.arange(3).reshape(3,1)
b = torch.tensor([1, 2])
a, b
a + b

tensor([[1, 2],
        [2, 3],
        [3, 4]])

运行一些操作，可能会导致为新结果分配内存

In [219]:
before = id(Y)
Y = X + Y
id(Y) == before

False

执行原地操作

In [220]:
Z = torch.zeros_like(Y) # 形成 shape和数据类型与 Y一致的张量
print('id(Z)=',id(Z))
Z[:] = X + Y
print('id(Z)=',id(Z))

id(Z)= 4818697776
id(Z)= 4818697776


In [221]:
before = id(Z)
Z += Y    # 使用该方法可以不改变 Z的位置，减少操作内存的开销
id(Z) == before

True

给定具有相同格式的张量，按任何元素二元计算的结果都是同样格式的张量

In [222]:
A = torch.arange(20, dtype=torch.float32).reshape(5,4)
B = A.clone()
print(A, A+B)
print(A*B) # 逐元素相乘, 内积
A == B # 判断两个张量是否相等

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]]) tensor([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.],
        [24., 26., 28., 30.],
        [32., 34., 36., 38.]])
tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [223]:
a = 2
X = torch.arange(12).reshape(3,4)
a+X, (a*X).shape # 2+X是一个标量和张量的运算,每个元素都加上2

(tensor([[ 2,  3,  4,  5],
         [ 6,  7,  8,  9],
         [10, 11, 12, 13]]),
 torch.Size([3, 4]))

装换为Numpy张量

In [224]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

将大小为1的张量转换为python的标量

In [225]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)  # item 用于提取张量元素

(tensor([3.5000]), 3.5, 3.5, 3)

---------------------------------------------------------------------------------------------------------------------------------------

➡️ 数据预处理

创建一个人工数据集，并储存在csv文件中

In [226]:
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = (os.path.join('..', 'data', 'house_tiny.csv'))
with open (data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n') # 列名
    f.write('NA,Pave,172500\n') #每行表示一个数据样本，NA表示缺失值
    f.write('2,NA,127500\n')
    f.write('4,NA,178900\n')
    f.write('NA,NA,140000\n')

从创建的csv文件中读取原始数据集

In [227]:
import pandas as pd
data = pd.read_csv(data_file) #read_csv 可以用于读取csv文件数据
print(data)
data


   NumRooms Alley   Price
0       NaN  Pave  172500
1       2.0   NaN  127500
2       4.0   NaN  178900
3       NaN   NaN  140000


,NumRooms,Alley,Price
0,NaN,Pave,172500
1,2.0,NaN,127500
2,4.0,NaN,178900
3,NaN,NaN,140000


为了处理缺失数据，我们可以采用 插值和删除的方法

In [228]:
inputs , outputs = data.iloc[:, 0:2], data.iloc[:, 2] #iloc为index location, 用于索引
inputs = inputs.fillna(inputs.mean(numeric_only=True))
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


对于inputs中的类别值或离散值，我们将NAN视为一种类别值

In [229]:
inputs = pd.get_dummies(inputs, dummy_na=True) # get_dummies 将类别特征转换为数值特征
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       3.0        True      False
1       2.0       False       True
2       4.0       False       True
3       3.0       False       True


现在inputs和outputs都是数值，则可以转为张量

In [230]:
# 确保 inputs 和 outputs 是数值类型
import torch
inputs = inputs.astype('float32') # astype 用于转换数据类型
# 转换为pytorch张量
x, y = torch.tensor(inputs.values), torch.tensor(outputs.values)
x, y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]]),
 tensor([172500, 127500, 178900, 140000]))