➡️ 深度学习数据处理📊

生成张量

In [5]:
import torch
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

显示数据格式

In [6]:
x.shape

torch.Size([12])

In [7]:
x.numel()

12

更改数据格式

In [8]:
X= x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

张量赋值

In [9]:
x = torch.zeros((2,3,4))
x

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
x = torch.ones((2,4,5))
x

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [11]:
x = torch.tensor([1.0,2,3,4])
y = torch.tensor([3,5,6,7])
x+y, x-y, x*y, x/y, x**y

(tensor([ 4.,  7.,  9., 11.]),
 tensor([-2., -3., -3., -3.]),
 tensor([ 3., 10., 18., 28.]),
 tensor([0.3333, 0.4000, 0.5000, 0.5714]),
 tensor([1.0000e+00, 3.2000e+01, 7.2900e+02, 1.6384e+04]))

In [12]:
x.sum() # 对x求和

tensor(10.)

In [13]:
torch.exp(x) #指数计算

tensor([ 2.7183,  7.3891, 20.0855, 54.5982])

处理张量

In [14]:
X = torch.arange(12,dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0,3,4,7],[3,4,5,6],[1,7,3,2]])
torch.cat((X, Y), dim=0),torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  3.,  4.,  7.],
         [ 3.,  4.,  5.,  6.],
         [ 1.,  7.,  3.,  2.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  3.,  4.,  7.],
         [ 4.,  5.,  6.,  7.,  3.,  4.,  5.,  6.],
         [ 8.,  9., 10., 11.,  1.,  7.,  3.,  2.]]))

In [15]:
X == Y # 布尔值运算

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [16]:
X[0:3],X[-1] # -1可以用来访问张量最后一行，0:3访问前三行

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([ 8.,  9., 10., 11.]))

In [17]:
X[2,3] = 9 # 用来对第三行，第四列的数字进行重写
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10.,  9.]])

In [18]:
X[:2, :] = 12 #用来对多个元素赋值相同值
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10.,  9.]])

两个张量形状不同，仍然可以使用广播机制

In [19]:
a = torch.arange(3).reshape(3,1)
b = torch.tensor([1, 2])
a, b
a + b

tensor([[1, 2],
        [2, 3],
        [3, 4]])

运行一些操作，可能会导致为新结果分配内存

In [20]:
before = id(Y)
Y = X + Y
id(Y) == before

False

执行原地操作

In [21]:
Z = torch.zeros_like(Y) # 形成 shape和数据类型与 Y一致的张量
print('id(Z)=',id(Z))
Z[:] = X + Y
print('id(Z)=',id(Z))

id(Z)= 4921471888
id(Z)= 4921471888


In [22]:
before = id(Z)
Z += Y    # 使用该方法可以不改变 Z的位置，减少操作内存的开销
id(Z) == before

True

装换为Numpy张量

In [23]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

将大小为1的张量转换为python的标量

In [24]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)  # item 用于提取张量元素

(tensor([3.5000]), 3.5, 3.5, 3)

---------------------------------------------------------------------------------------------------------------------------------------

➡️ 数据预处理

创建一个人工数据集，并储存在csv文件中

In [25]:
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = (os.path.join('..', 'data', 'house_tiny.csv'))
with open (data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n') # 列名
    f.write('NA,Pave,172500\n') #每行表示一个数据样本，NA表示缺失值
    f.write('2,NA,127500\n')
    f.write('4,NA,178900\n')
    f.write('NA,NA,140000\n')

从创建的csv文件中读取原始数据集

In [26]:
import pandas as pd
data = pd.read_csv(data_file) #read_csv 可以用于读取csv文件数据
print(data)
data


   NumRooms Alley   Price
0       NaN  Pave  172500
1       2.0   NaN  127500
2       4.0   NaN  178900
3       NaN   NaN  140000


,NumRooms,Alley,Price
0,NaN,Pave,172500
1,2.0,NaN,127500
2,4.0,NaN,178900
3,NaN,NaN,140000


为了处理缺失数据，我们可以采用 插值和删除的方法

In [35]:
inputs , outputs = data.iloc[:, 0:2], data.iloc[:, 2] #iloc为index location, 用于索引
inputs = inputs.fillna(inputs.mean(numeric_only=True))
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


对于inputs中的类别值或离散值，我们将NAN视为一种类别值

In [ ]:
inputs = pd.get_dummies(inputs, dummy_na=True) # get_dummies 将类别特征转换为数值特征
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       3.0        True      False
1       2.0       False       True
2       4.0       False       True
3       3.0       False       True


现在inputs和outputs都是数值，则可以转为张量

In [ ]:
# 确保 inputs 和 outputs 是数值类型
import torch
inputs = inputs.astype('float32') # astype 用于转换数据类型
# 转换为pytorch张量
x, y = torch.tensor(inputs.values), torch.tensor(outputs.values)
x, y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]]),
 tensor([172500, 127500, 178900, 140000]))